### ISSUE TITLE
Miscommunication from Client to Worker for local_directory argument

### ISSUE THREAD

**Issue by trhallam** [dask/distributed#3051]
The depreciated keyword `local_dir` for the `Worker` class passes ok via `Client` but the new keyword `local_directory` causes big problems. Primarily, `TypeError: __init__() got an unexpected keyword argument 'local_directory'`
```
Python 3.6.7 (default, Feb 28 2019, 07:28:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask.distributed import Client
>>> import tempfile
>>> tmp = tempfile.gettempdir()
>>> c1 = Client(local_dir=tmp)
>>> c1.close()
>>> c2 = Client(local_directory=tmp)
Process Process-7:
Traceback (most recent call last):
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\distributed\process.py", line 181, in _run
    target(*args, **kwargs)
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\distributed\nanny.py", line 587, in _run
    worker = Worker(*worker_args, **worker_kwargs)
  File "C:\Users\arh5\AppData\Local\Continuum\anaconda3\envs\etlp_conda_dev\lib\site-packages\distributed\worker.py", line 552, in __init__
    **kwargs
TypeError: __init__() got an unexpected keyword argument 'local_directory'
Process Process-6:
KeyboardInterrupt
>>>
```

**Comment by TomAugspurger** [comment]
What version of distributed? This works for me

```

In [3]: >>> c2 = Client(local_directory='/tmp')
In [4]: c2
Out[4]: <Client: 'tcp://127.0.0.1:53318' processes=4 threads=8, memory=17.18 GB>

```

**Comment by trhallam** [comment]
Version 1.28.1 -> should have checked because after updated to 2.4 the issue was resolved as you demonstrated. I installed using conda not that long ago so I'm a bit surprised the version was so far behind.

**Comment by jrbourbeau** [comment]
Closing as it looks like updating `distributed` resolved this issue. Feel free to re-open as needed @trhallam
