### ISSUE TITLE
Problem using as_completed

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1535]
On master (distributed==1.19.3+42.g7e1b481; dask==0.15.4; Python 2.7.14)

I get the following errors:
```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10701d520>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/client.py", line 3122, in track_future
    yield _wait(future)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/client.py", line 2988, in _wait
    fs = futures_of(fs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distributed/client.py", line 3290, in futures_of
    if dask.is_dask_collection(x):
AttributeError: 'module' object has no attribute 'is_dask_collection'
```
with the following simple test script
```python
from distributed import Client, as_completed

def inc(x):
  return x+1

client = Client()

x, y, z = client.map(inc, [1, 2, 3])  
for future in as_completed([x, y, z]):  
  print(future.result())  
```

**Comment by rbubley** [comment]
The same code works fine on release 1.19.3

**Comment by mrocklin** [comment]
You need to install dask from git master

    pip install git+https://github.com/dask/dask.git --upgrade --no-deps
