### ISSUE TITLE
TypeError: rechunk() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#7628]
Our CI jobs are currenlty failing with the exception

`TypeError: rechunk() got an unexpected keyword argument 'method'`

This is caused by https://github.com/dask/dask/pull/10013 but was already fixed by https://github.com/dask/distributed/pull/7623

For example https://github.com/dask/distributed/actions/runs/4364430616/jobs/7631747110

I assume this is due to a stale cache. I'll see if I can delete a cache manually

**Comment by fjetter** [comment]
I cleared todays cache and will retrigger CI once on main to repopulate with a hopefully functioning version

**Comment by hendrikmakait** [comment]
Until caches have been invalidated globally, `git commit -m "[skip-caching]" --allow-empty` on individual PRs should solve the pain.

**Comment by jrbourbeau** [comment]
> Until caches have been invalidated globally

Is there a mechanism we can use for invalidating globally?

**Comment by hendrikmakait** [comment]
> Is there a mechanism we can use for invalidating globally?

None that I' aware of apart from waiting for a day. We may want to consider always excluding the installation of `dask/dask` from the cached environment and always install it alongside `dask/distributed`.
