### PR TITLE
Add version check for absolute url fix

### LINKED ISSUE #8380: Dashboards fail with 500 status code when using `bokeh<3.3.0`
When using the latest `main` with `bokeh<3.3.0`, the dashboards fail with a 500 status code.

Scheduler traceback:
```
2023-11-30 18:00:07,300 - tornado.application - ERROR - Uncaught exception GET /status (192.168.178.45)
HTTPServerRequest(protocol='http', host='192.168.178.45:8787', method='GET', uri='/status', version='HTTP/1.1', remote_ip='192.168.178.45')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/server/views/doc_handler.py", line 57, in get
    resources=self.application.resources(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hendrikmakait/projects/dask/distributed/distributed/dashboard/core.py", line 37, in resources
    return super().resources(absolute_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/server/tornado.py", line 621, in resources
    return Resources(mode="server", root_url=root_url, path_versioner=StaticHandler.append_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/resources.py", line 377, in __init__
    if root_url and not root_url.endswith("/"):
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'endswith'
```

git bisect blames #8347

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Closes #8380

In #8347 I added a workaround for a breaking change introduced in bokeh `3.3.0`. It turns out it wasn't as backward compatible as I thought, so this PR puts the shim behind a version check.

### CODE REVIEW

**Comment by fjetter** [comment]
I'm fine with the fix but am wondering if this is something we can test. we have the mindeps build for the lower versions so I would hope we can cover both cases.

**Review by hendrikmakait — APPROVED** [review]
Thanks, @jacobtomlinson for the quick turnaround. 

@fjetter: I agree that it would be good to have tests for the dashboards with the minimum version of bokeh. From what I see though, `mindeps` does not include `bokeh` as it's an optional dependency. We could add another build, but that will require more work than simply adding a single test. I'd rather merge this PR to include it in the release than delay it due to missing automated tests. I've tested this manually and the fix works, so I'd propose adding tests in a follow-up PR.

**Comment by jacobtomlinson** [comment]
Yeah I agree it would be the right thing to do but didn't bother right now with a test when I spotted it wasn't included in mindeps.
