### ISSUE TITLE
Dashboards fail with 500 status code when using `bokeh<3.3.0`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8380]
When using the latest `main` with `bokeh<3.3.0`, the dashboards fail with a 500 status code.

Scheduler traceback:
```
2023-11-30 18:00:07,300 - tornado.application - ERROR - Uncaught exception GET /status (192.168.178.45)
HTTPServerRequest(protocol='http', host='192.168.178.45:8787', method='GET', uri='/status', version='HTTP/1.1', remote_ip='192.168.178.45')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/server/views/doc_handler.py", line 57, in get
    resources=self.application.resources(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hendrikmakait/projects/dask/distributed/distributed/dashboard/core.py", line 37, in resources
    return super().resources(absolute_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/server/tornado.py", line 621, in resources
    return Resources(mode="server", root_url=root_url, path_versioner=StaticHandler.append_version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-distributed/lib/python3.11/site-packages/bokeh/resources.py", line 377, in __init__
    if root_url and not root_url.endswith("/"):
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'endswith'
```

git bisect blames #8347

**Comment by fjetter** [comment]
#8347 hasn't been released, yet. @jacobtomlinson do you have time to look at this?

**Comment by jacobtomlinson** [comment]
@hendrikmakait which version of bokeh do you have? I've just tested distributed `main` against `3.3.0`, `3.2.2`, `3.1.1` and `2.4.2` (the min dep) and I can't reproduce.

**Comment by hendrikmakait** [comment]
I'll wipe my development environment including all directories and see if this issue still pops up.

**Comment by jacobtomlinson** [comment]
Ah I figured out the difference. The problem happens if I create a `LocalCluster`.

```python
from dask.distributed import Client
client = Client()
print(client.dashboard_link)
```

**Comment by hendrikmakait** [comment]
> Ah I figured out the difference. The problem happens if I create a `LocalCluster`.
> 
> ```python
> from dask.distributed import Client
> client = Client()
> print(client.dashboard_link)
> ```

My bad, I should've specified how I instantiate the scheduler. I use `dask scheduler` and the error pops up when I actually _visit_ the dashboard.

**Comment by jacobtomlinson** [comment]
Maybe my dev environment is a bit confused too. Let me make a new env.

**Comment by jacobtomlinson** [comment]
Leave it with me, I'm putting a fix together now.

**Comment by hendrikmakait** [comment]
Jumping through the source code in VS Code leads to this definition of `BokehTornado.resources` which does not expect a `bool` as input input. However, #8347 defaults to `True`.

```python3
    def resources(self, absolute_url: str | None = None) -> Resources:
        ''' Provide a :class:`~bokeh.resources.Resources` that specifies where
        Bokeh application sessions should load BokehJS resources from.

        Args:
            absolute_url (bool):
                An absolute URL prefix to use for locating resources. If None,
                relative URLs are used (default: None)

        '''
        mode = settings.resources(default="server")
        if mode == "server" or mode == "server-dev":
            root_url = urljoin(absolute_url or self._absolute_url or "", self._prefix)
            return Resources(mode="server", root_url=root_url, path_versioner=StaticHandler.append_version)
        return Resources(mode=mode)
```

**Comment by jacobtomlinson** [comment]
Yeah the patch suggested by @bryevdv was to change the default to `True` because we can't explicitly set this anywhere.

However looking at the source of `2.4.2` we still need this to be `None`. Given we are working around a breaking change in `3.3.0` I wonder if we need to check the bokeh version and only do this in newer versions of `bokeh`.
