### ISSUE TITLE
Problem launching LocalCluster with old bokeh installed

### ISSUE THREAD

**Issue by rbubley** [dask/distributed#1295]
With distributed==1.18.0 and bokeh=0.12.3, I get

```
$ python
Python 2.7.13 (default, Apr 23 2017, 16:50:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from distributed import Client, LocalCluster
>>> cluster = LocalCluster()
tornado.application - ERROR - Exception in callback <functools.partial object at 0x102c4d578>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bokeh/server/tornado.py", line 439, in _start_async
    self.exit(1)
AttributeError: 'BokehTornado' object has no attribute 'exit'
```

This is resolved by upgrading bokeh to a newer version (it works with 0.12.6).

Submitting in case anyone else bumps into this.
