### ISSUE TITLE
SVD Fails with CuPy 7.0+ (master)

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3353]
When using latest CuPy and trying to compute an svd with dask, we get an error:

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "cpu-svd.py", line 10, in <module>
    u.compute()
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/optimization.py", line 982, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/dask/array/linalg.py", line 48, in _wrapped_qr
    return np.linalg.qr(a)
  File "<__array_function__ internals>", line 6, in qr
  File "cupy/core/core.pyx", line 1344, in cupy.core.core.ndarray.__array_function__
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/cupy/linalg/decomposition.py", line 248, in qr
    geqrf, dev_info)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-12/lib/python3.7/site-packages/cupy/linalg/util.py", line 42, in _check_cusolver_dev_info_if_synchronization_allowed
    print(cupyx._ufunc_config.config.linalg)
AttributeError: '_thread._local' object has no attribute 'linalg'
```
</details>

Reproducible Example:

```python
import dask, cupy
import dask.array as da

rs = dask.array.random.RandomState(RandomState=cupy.random.RandomState)
x = rs.random((100, 100))
x = x.persist()
u, s, v = da.linalg.svd(x)
u.compute()
```

The error arises from the cupy call here:
https://github.com/cupy/cupy/blob/f06f509167957240d17924965238cb0901b700ab/cupy/linalg/util.py#L37

It seems that the `cupyx._ufunc_config` is a `_thread._local` object at the time of execution.  

*Note: when using `u.compute(scheduler='singled-threaded')` there is now issue*

@pentschev do you have thoughts on what might be happening here ?

**Comment by pentschev** [comment]
> When using latest CuPy

Does that mean it works with an older one, or are you just stating that you're up-to-date?

**Comment by quasiben** [comment]
I believe it works with 6.6.0

**Comment by quasiben** [comment]
Maybe this is a threading issue within CuPy:

https://github.com/cupy/cupy/blob/f06f509167957240d17924965238cb0901b700ab/cupyx/_ufunc_config.py#L4-L13

**Comment by quasiben** [comment]
Added a CuPy issue:
https://github.com/cupy/cupy/issues/2911

**Comment by pentschev** [comment]
Does https://github.com/cupy/cupy/pull/2915 solve this issue? Can we close it here?

**Comment by quasiben** [comment]
yes, we can close.  I should've done this earlier
